// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/overview": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/overview";
  };
  "routes/overview.tsx": {
    id: "routes/overview";
    page: "/overview";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/overview": typeof import("./src/app/routes/overview.tsx");
  "routes/_index": typeof import("./src/app/routes/_index.tsx");
};